[project]
name = "sa-metameta"
version = "0.1.0"
description = "Dynamic SQLAlchemy Metadata Reflection of One or More SQLALchemy Engines"
authors = [
    {name = "48.41.50",email = "48.41.50@gmail.com"}
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "psycopg[binary] (>=3.3.4,<4.0.0)"
]

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "ipython (>=9.17.0,<10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
